import "./globals.css";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth bg-black ">
      <body className={[inter.className, "bg-black text-white"]}>
        <Toaster position="bottom-right" />
        {children}
        <Footer />
      </body>
    </html>
  );
}
